apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-chwv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/bootstrap/nbe-e2e-xnbw-tenant/integ-app-mvne/hacbs-test-project-chwv@sha256:3b89bc343212651405ef027b7d6ddf3e456e43538ef58dfa62009b0c815840d2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
